### ISSUE TITLE
does this code deal with random mask?

### ISSUE THREAD

**Issue by micklexqg** [neka-nat/image_completion_keras#11]
Hi, as the title, sorry for that I have not run successfully the code for now so i did not know it it can  fulfill random inpainting. I noticed the script in https://github.com/nekanat/image_completion_keras/blob/master/train.py.
may be the code can fulfill random inpainting? is it?

**Comment by neka-nat** [comment]
Hi, @micklexqg .
Yes, this code can fulfill random inpainting.
In the `flow` method of `Datagenerator`, bounding boxies are generated randomly.

You mentioned you couldn't run successfully the code.
What kind of trouble does it have?

**Comment by micklexqg** [comment]
@neka-nat , thanks for reply. because I am working on fulfill random inpainting based on another inpainting model.  so an unconsidered trouble. maybe later I will try your code and perhaps need to consult you...
