### ISSUE TITLE
which branch should I choose?

### ISSUE THREAD

**Issue by xieenze** [neka-nat/image_completion_keras#3]
Hello, I find you have three branches in this project, and you last submit your code in the anim branch.
Can you tell me the difference between these three branches if you are in  rest?
Thanks a lot

**Comment by neka-nat** [comment]
Hi, xieeze.
anim branch is for an application of animation or movies.
Now, I check the pull request branch which is implemented joint loss.
After that, I will merge to the master branch.

**Comment by neka-nat** [comment]
I merged the pull request branch.
Please try it.
Thank you.
