### ISSUE TITLE
Can't training the model on GPU

### ISSUE THREAD

**Issue by generallc** [neka-nat/image_completion_keras#4]
Hello, I can train your model on CPU with the following configuration:CUDA8.0    Tensorflow(1.6.0)   Keras (2.1.5) . 
But when I install Tensorflow-gpu(1.6.0) instead of  Tensorflow(1.6.0), the program does not work ,even if I tried Tensorflow-gpu1.5.0 to 1.0.0. My GPU is NVIDIA 1080.
Could you please find the error and tell me about your configuration of CUDA ,Tensorflow and so on,which is not showing in yout 'requirements.txt'.
Thanks !

**Comment by generallc** [comment]
And could you please  tell me what the following code is for ：

**Comment by neka-nat** [comment]
Hi,
I use CUDA9 and cudnn7.
And I updated requirements.txt  added version information.
Please check it and can I see the error messages if you still found the error?

**Comment by generallc** [comment]
After I input 'python train.py', the following errors occurred：
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/install_sources#common_installation_problems
for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by generallc** [comment]
I have solved the problem, First I change cuda from 8.0 to 9.0, the error became “libcublas.so.6.0”.  Then I installed cudnn6.0. The  model can run the GPU. I think it is a version issue. Thanks
